# Generated by Django 2.2 on 2021-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redzoneuser',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
