# Generated by Django 2.2 on 2021-04-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20210404_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redzoneuser',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
