# Generated by Django 2.2 on 2021-04-05 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20210404_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covid_positive', models.BooleanField()),
                ('visited_outside', models.BooleanField()),
                ('other_interaction', models.BooleanField()),
                ('wore_mask', models.BooleanField()),
                ('wore_ppe', models.BooleanField()),
                ('location', models.CharField(max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
