# Generated by Django 2.2 on 2021-04-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redzoneuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redzoneuser',
            name='profession',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='profession'),
        ),
    ]
